import Head from 'next/head'
import Sidebar from '../components/Sidebar'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://help.twitter.com/content/dam/help-twitter/brand/logo.png" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto '>
       {/*slider*/}
      <Sidebar ></Sidebar>
      {/*Feed*/}

      {/*Widgets*/} 
      </main>
      
    </div>
  )
}
