import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'



export default function Home({newsResults}) {
  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://help.twitter.com/content/dam/help-twitter/brand/logo.png" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto '>
       {/*slider*/}
      <Sidebar ></Sidebar>
      {/*Feed*/}
      <Feed />

      {/*Widgets*/} 

      <Widgets newsResults={newsResults.articles} />
      </main>
      
    </div>
  )
}

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
      
    },
  };
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/in.json